version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create:migrate

      - run:
          name: Parallel RSpec
          command: bin/rails test
