version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # - save_cache:
      #     key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
      #     paths:
      #       - vendor/bundle

      # - run:
      #     name: Database Setup
      #     command: |
      #       bundle exec rake db:create:migrate

      # - run:
      #     name: Parallel RSpec
      #     command: rspec
